const routeMap = {
  login: "/auth/login",
  placeOrder: "/place-order",
  bookings: "/bookings",
  orderHistory: "/order-history",
  todaysPickup: "/pickup",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  otpVerification: "/auth/otp-verification",
  dashboard: "/dashboard",
  rolesNPermission: "/roles-and-permissions",
  inviteAdmin: "/roles-and-permissions/invite-admin",
  adminDetails: "/roles-and-permissions/details",
  userManagement: "/user-management",
  userDetails: "/user-management/:id",
  settings: "/settings",
  orderManagement: "/order-management",
  orderDetails: "/order-management/order-details/:id",
  conciergeDetails: "/order-management/concierge-details/:id",
  transactionManagement: "/transaction-management",
  transactionDetails: "/transaction-management/:id",
  riderManagement: "/rider-management",
  riderDetails: "/rider-management/rider-details",
  deliveryDetails: "/rider-management/delivery-details",
  auditTrail: "/audit-trail",
  notifications: "/notifications",
  earningsManagement: "/earnings-management",
  earningsDetails: "/earnings-management/details",
  loyaltySettings: "/earnings-management/loyalty-settings",
  promotionsManagement: "/promotions-management",
  reportAndAnalytics: "/report-analytics",
  moreReports: "/report-analytics/more",
  walletManagement: "/wallet-management",
  walletTransactions: "/wallet-management/transactions/:id",
};

export default routeMap;
